$(document).ready(function(){
  $('.navDD').on('click',function(){
    $('.ddNavs').slideToggle();
  })
  $(window).scroll(function(){
    if($(window).scrollTop()>10){
      $('.navContainer').addClass('navContainer-scroll')
    }
    else{
      $('.navContainer').removeClass('navContainer-scroll')
    }
  })
})
